### ISSUE TITLE
Tracking broken components needing re-release

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#22983]
This issues tracks components that have been integrated in GlassFish already, but cause various breakages such as OSGi or other class loader issues. 

Note that https://github.com/eclipse-ee4j/glassfish/issues/22938 is for components that we haven't integrated yet, and are looking for to be fixed first.

- [x] batch api/m2 https://github.com/eclipse-ee4j/batch-api/pull/30
- [x] mail api/rc5 https://github.com/eclipse-ee4j/mail/pull/448
- [x] ejb api/rc2 https://github.com/eclipse-ee4j/ejb-api/pull/81
- [x] jta api/rc2 https://github.com/eclipse-ee4j/jta-api/pull/94
- [x] jsftemplating/m2  https://github.com/eclipse-ee4j/glassfish-jsftemplating/pull/73
- [x] mojarra/rc2 https://github.com/eclipse-ee4j/mojarra/pull/4705
- [ ] yasson/2.0.0-M2 https://github.com/eclipse-ee4j/yasson/pull/411
- [ ] tyrus/2.0.0-M2 https://github.com/eclipse-ee4j/tyrus/pull/701
- [x] jaxb-ri/3.0.0-M3 https://github.com/eclipse-ee4j/jaxb-ri/pull/1453
- [x] webservices-osgi/3.0.0-M2 https://github.com/eclipse-ee4j/metro-wsit/pull/86 https://github.com/eclipse-ee4j/metro-wsit/issues/85
- [ ] HK2/3.0.0-M2 https://github.com/eclipse-ee4j/glassfish-hk2/pull/512

**Comment by smillidge** [comment]
Can we split this issue out into individual issues as it provides greater visibility to other teams?

**Comment by smillidge** [comment]
I am closing this as I have created 
https://github.com/eclipse-ee4j/glassfish/issues/23044
https://github.com/eclipse-ee4j/glassfish/issues/23045
https://github.com/eclipse-ee4j/glassfish/issues/23046

and the equivalent issues on the upstream projects
